name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - uses: cloudflare/wrangler-action@1.3.0
      with:
        apiToken: ${{ secrets.CF_PAGES_API_TOKEN }}
        
    - name: Restore dependencies
      run: dotnet restore 
      working-directory: nacara-site/blog-layout
    
    - name: Restore tools
      run: dotnet tool restore --tool-manifest
      working-directory: nacara-site/blog-layout

    - name: Build
      run: dotnet build --no-restore 
      working-directory: nacara-site/blog-layout

    - name: Fable Build
      run: dotnet fable --outdir dist
      working-directory: nacara-site/blog-layout

    - name: Npm install/restore
      run: npm install
      working-directory: nacara-site/

    - name: Nacara Build
      run: npm run build
      working-directory: nacara-site/
